### PR TITLE
fetchn_fafb/nblast_fafb takes neuronlist as input

### PR DESCRIPTION
**Pull request by zhihaozheng**
So people with no access to FAFB Catmaid can nblast pre-downloaded FAFB neurons.

### CODE REVIEW

**Comment by jefferis** [comment]
Do you want to roxygenise?

**Comment by jefferis** [comment]
Thanks – have been meaning to make a change like this for a while. Would it be possible to give an example as well e.g. using the `dense_core_neurons` object built into elmr.

**Comment by zhihaozheng** [comment]
Sure will update the PR soon after roxygenise and addition of an example.

**Comment by zhihaozheng** [comment]
roxygenize, add a templatebrain check, and add examples in fetchn_fafb/nblast_fafb. You can use the latest PR commit.

**Comment by jefferis** [comment]
Thanks again @zhihaozheng!

**Pull request merged**
